version: '3'
services:
  node-app:
    build: ./app
    ports:
     - "3000:3000"
    depends_on:
     - redis
  redis:
    image: redis
    ports:
        - "6379:6379"

  azure-vote-front:
    build: ./azure-vote
    image: azure-vote-front
    container_name: azure-vote-front
    environment:
      REDIS: redis
    ports:
        - "8080:80"
